spring:
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_5_DEVINT?useSSL=false&allowPublicKeyRetrieval=true
    username: CSCI5308_5_DEVINT_USER
    password: ahthi6ohHe
    # url: jdbc:mysql://localhost:3306/asdc_g5
    # username: root
    # password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: housingease
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: housingease05@gmail.com
    password: rkgf hyhx cxbh ybbz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
